### ISSUE TITLE
Does not support 1.21 features

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Vanilla-Data#129]
Self-explanatory. I believe this is the correct repo since the diagnoser was flagging the wind charge's geometry as not existing.

**Comment by DaanV2** [comment]
Sorry, couldnt you explain this one more? You mentioned geometry, but the title is about features?

**Comment by Xterionix** [comment]
I mean like stuff in the vanilla repo for 1.21 isn't being counted

**Comment by Xterionix** [comment]
I created an entity using wind charge assets and it was flagged as non-existent

**Comment by Xterionix** [comment]
@DaanV2

**Comment by Xterionix** [comment]
The plugin hadn't updated that's why it was flagging it as invalid.
