### ISSUE TITLE
Github files aren't updated to 1.21

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Vanilla-Data#133]
https://github.com/Blockception/BC-Minecraft-Bedrock-Vanilla-Data/blob/main/src/Lib/Vanilla/sources.ts

Does not list files from 1.21

**Comment by DaanV2** [comment]
Any examples? Cause Im seeing files included, that's in 1.21: https://github.com/Blockception/BC-Minecraft-Bedrock-Vanilla-Data/pull/132 🤔

**Comment by Xterionix** [comment]
Ah yeah you're right, is the extension updated to this because I'm not seeing of the 1.21 stuff?

**Comment by DaanV2** [comment]
No, did an update on animation_controllers for that player.json issue, which I still need to process 😬

**Comment by Xterionix** [comment]
Lovely, anyways this can be closed.
