### ISSUE TITLE
Painting entity not recognized in mcfunction commands

### ISSUE THREAD

**Issue by sparks0** [Blockception/BC-Minecraft-Bedrock-Vanilla-Data#38]
**Describe the bug**
In an mcfunction file, typing "@e[type=painting]" or "@e[type=minecraft:painting]" causes the error "Cannot find entity definition: minecraft:painting".

**To Reproduce**
1. Open an mcfunction file in a behavior pack
2. Type `kill @e[type=painting]` onto a new line
3. Observe red syntax error highlight

**Expected behavior**
Painting should be a valid entity in the selector.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.2.89

**Comment by DaanV2** [comment]
The minecraft:painting entity does not exist in the vanilla data causing this problem, adding this to the vanilla data set would solve this, going to look into it a while later

**Comment by DaanV2** [comment]
Processed in the new patch
